### ISSUE TITLE
Users can track their mood day by day.

### ISSUE THREAD

**Issue by s-shaligram** [s-shaligram/Mental-health-care#3]
As a user, I can **track my mood day by day.**

**Comment by kavin256** [comment]
Delayed to Sprint #2

**Comment by s94wanniarachchige** [comment]
This feature is more complicated than we initially anticipated .Because of that  we'll going to complete this in the next sprint.

**Comment by s-shaligram** [comment]
This issue is split into two separate features; 
1. Users can select emojis to express the mood
2. Users can record their day by day mood

**Comment by s-shaligram** [comment]
Enhancement feature implemented.
Users can record their day by day mood and show the progress history #50
